apiVersion: v1
kind: Service
metadata:
  name: arp-survey
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.44.208
  selector:
    app: arp-survey
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
