"""add telescope CCD specs and target magnitude

Revision ID: 4bfee6d560b0
Revises: e9018227216e
Create Date: 2026-04-17 22:36:44.267450
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4bfee6d560b0'
down_revision: Union[str, None] = 'e9018227216e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('magnitude', sa.Float(), nullable=True))
    op.add_column('telescopes', sa.Column('focal_length_mm', sa.Float(), nullable=True))
    op.add_column('telescopes', sa.Column('pixel_size_um', sa.Float(), nullable=True))
    op.add_column('telescopes', sa.Column('peak_qe', sa.Float(), nullable=True))
    op.add_column('telescopes', sa.Column('full_well_e', sa.Integer(), nullable=True))
    op.add_column('telescopes', sa.Column('camera_model', sa.String(length=80), nullable=True))
    op.add_column('telescopes', sa.Column('sensor_model', sa.String(length=80), nullable=True))
    op.add_column('telescopes', sa.Column('sensor_type', sa.String(length=20), nullable=True))
    op.add_column('telescopes', sa.Column('read_noise_e', sa.Float(), nullable=True))
    op.add_column('telescopes', sa.Column('dark_current_e', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telescopes', 'dark_current_e')
    op.drop_column('telescopes', 'read_noise_e')
    op.drop_column('telescopes', 'sensor_type')
    op.drop_column('telescopes', 'sensor_model')
    op.drop_column('telescopes', 'camera_model')
    op.drop_column('telescopes', 'full_well_e')
    op.drop_column('telescopes', 'peak_qe')
    op.drop_column('telescopes', 'pixel_size_um')
    op.drop_column('telescopes', 'focal_length_mm')
    op.drop_column('targets', 'magnitude')
    # ### end Alembic commands ###
