"""initial schema

Revision ID: e9018227216e
Revises: 
Create Date: 2026-04-17 18:02:49.141212
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9018227216e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon_calendar_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('site_key', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('phase_calendar', sa.JSON(), nullable=False),
    sa.Column('next_new_moon', sa.Date(), nullable=True),
    sa.Column('next_full_moon', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('site_key', sa.String(length=30), nullable=False),
    sa.Column('date_local', sa.Date(), nullable=False),
    sa.Column('eve_twilight', sa.DateTime(), nullable=False),
    sa.Column('morn_twilight', sa.DateTime(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arp_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('ra_hours', sa.Float(), nullable=False),
    sa.Column('dec_degrees', sa.Float(), nullable=False),
    sa.Column('ra_catalog', sa.String(length=30), nullable=True),
    sa.Column('dec_catalog', sa.String(length=30), nullable=True),
    sa.Column('ned_ra_hours', sa.Float(), nullable=True),
    sa.Column('ned_dec_degrees', sa.Float(), nullable=True),
    sa.Column('ned_name', sa.String(length=120), nullable=True),
    sa.Column('size_arcmin', sa.Float(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('best_site', sa.String(length=40), nullable=True),
    sa.Column('filter_strategy', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arp_number')
    )
    op.create_table('telescopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telescope_id', sa.String(length=10), nullable=False),
    sa.Column('site', sa.String(length=30), nullable=False),
    sa.Column('fov_arcmin', sa.Float(), nullable=True),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('aperture_mm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telescope_id')
    )
    op.create_table('generated_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('telescope_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['telescope_id'], ['telescopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imaging_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('date_imaged', sa.Date(), nullable=False),
    sa.Column('telescope_id', sa.Integer(), nullable=True),
    sa.Column('filter_strategy', sa.String(length=20), nullable=True),
    sa.Column('exposure_minutes', sa.Float(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.ForeignKeyConstraint(['telescope_id'], ['telescopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moon_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('night_date', sa.Date(), nullable=False),
    sa.Column('phase_pct', sa.Float(), nullable=True),
    sa.Column('separation_deg', sa.Float(), nullable=True),
    sa.Column('risk', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'night_date', name='uq_moon_target_date')
    )
    op.create_index('ix_moon_date_risk', 'moon_data', ['night_date', 'risk'], unique=False)
    op.create_table('telescope_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telescope_id', sa.Integer(), nullable=False),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('session_rate', sa.Float(), nullable=True),
    sa.Column('exposure_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['telescope_id'], ['telescopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telescope_id', 'plan_tier', name='uq_telescope_plan')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telescope_rates')
    op.drop_index('ix_moon_date_risk', table_name='moon_data')
    op.drop_table('moon_data')
    op.drop_table('imaging_log')
    op.drop_table('generated_plans')
    op.drop_table('telescopes')
    op.drop_table('targets')
    op.drop_table('session_results')
    op.drop_table('moon_calendar_runs')
    # ### end Alembic commands ###
